### ISSUE TITLE
Requires to manually create index.ios.js and index.android.js

### ISSUE THREAD

**Issue by ddzirt** [JonnyBurger/npx-visualize-bundle#1]
Running ` npx visualize-bundle ` on react-native project(not expo) requires to have ` index.ios.js ` and ` index.android.js ` which is a bit(just a bit, but still) of manual work. 

Most likely issue comes from here:
https://github.com/ddzirt/npx-visualize-bundle/blob/32035b51df78bc24a219102928c856925b2a857b/src/index.ts#L85

And this also means that running ` npx visualize-bundle -a ` will require ` index.ios.js ` to be present for android and this is even more inconvenient for the end user.

**Comment by JonnyBurger** [comment]
Thanks for the helpful report!
I think I fixed this and released a new version, 1.1.0.

Do you want to try it close the issue if it now works for you?

**Comment by ddzirt** [comment]
I’ll look at it, and if everything is ok, I’ll close the issue

**Comment by ddzirt** [comment]
> Thanks for the helpful report!
> I think I fixed this and released a new version, 1.1.0.
> 
> Do you want to try it close the issue if it now works for you?

Works like a charm!
