### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dom' of undefined

### ISSUE THREAD

**Issue by slavikdenis** [JonnyBurger/npx-visualize-bundle#8]
While trying to run `npx visualize-bundle -a -d -o ./`, I'm running into an issue on the generated html file `Uncaught TypeError: Cannot read property 'dom' of undefined`.

If you need any more details on this issue, please let me know. Thanks

![image](https://user-images.githubusercontent.com/15640932/58790451-b497c000-85f0-11e9-9434-f0d200eb866b.png)

**Comment by JonnyBurger** [comment]
Thanks for filing the issue!

Can you try to feed the result into https://www.npmjs.com/package/source-map-explorer directly and see if the this might be a bug in source-map-explorer?

Alternatively it could be the `-o` flag. Does the problem remain if you remove it?

**Comment by slavikdenis** [comment]
Removing the `-o` flag does not help.

---

After saving the bundle from
`http://localhost:8081/index.bundle?platform=android&sourceMap=true&dev=true&minify=false&hot=false`
as *bundle.js* and the source map from
`http://localhost:8081/index.map?platform=android&sourceMap=true&dev=true&minify=false&hot=false`
as *bundle.js.map* ,
I had to edit the raw bundle last line from
`//# sourceMappingURL=http://localhost:8081/index.map?platform=android&sourceMap=true&dev=true&minify=false&hot=false`
to 
`//# sourceMappingURL=bundle.js.map`.

After I ran `npx source-map-explorer bundle.js{,.map}` and only after these steps I successfully generated the report.

![image](https://user-images.githubusercontent.com/15640932/58899716-ec405e00-86fd-11e9-8a30-ec2bcb5d0599.png)

Not completely sure if these are the standard steps to succeed tho :D

**Comment by JonnyBurger** [comment]
Hi Denis!

Thanks that is very helpful!
While I do not experience the error, I have made a PR here: #9 

Could you check out this PR and try to see if it works? You can start the tool locally just with `npm install` followed by `npm start`.

**Comment by slavikdenis** [comment]
Unfortunatly the *prepare* script is failing for me probably because I'm on windows and 
`tsc && echo "#! /usr/bin/env node" | cat - dist/index.js > /tmp/out
&& mv /tmp/out dist/index.js`
is not cross-platform.

I will look into the solution for windows later and let you know.

**Comment by slavikdenis** [comment]
@JonnyBurger sorry for the delay. I just tried out your PR but unfortunately without success :/ Do not worry to close this issue and reopen it  when someone else runs into this issue as well.

**Comment by JonnyBurger** [comment]
Thanks for getting back!
If somebody has more info please comment here 😊
